import {
  SiCss,
  SiExpress,
  SiFigma,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiTailwindcss,
} from "react-icons/si";
import { VscCode } from "react-icons/vsc";

export const skillIconMap = {
  html5: SiHtml5,
  css3: SiCss,
  javascript: SiJavascript,
  react: SiReact,
  nextjs: SiNextdotjs,
  tailwind: SiTailwindcss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  python: SiPython,
  mongodb: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  git: SiGit,
  figma: SiFigma,
  vscode: VscCode,
  postman: SiPostman,
};

export const skillIconColors = {
  html5: "text-[#E34F26]",
  css3: "text-[#1572B6]",
  javascript: "text-[#F7DF1E]",
  react: "text-[#61DAFB]",
  nextjs: "text-white",
  tailwind: "text-[#38BDF8]",
  nodejs: "text-[#339933]",
  express: "text-white",
  python: "text-[#3776AB]",
  mongodb: "text-[#47A248]",
  mysql: "text-[#4479A1]",
  postgresql: "text-[#4169E1]",
  git: "text-[#F05032]",
  figma: "text-[#F24E1E]",
  vscode: "text-[#007ACC]",
  postman: "text-[#FF6C37]",
};
